name: Media Definition Validator

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout the head ref instead of the PR branch that github creates.
        ref: ${{ github.head_ref }}
    - name: Setup Node.js v12
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - name: Install and build
      run: |
        npm ci
        npm run compile
    - name: Run status checks
      run: node dist/validator.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: docker://github/super-linter:v3.17.2@sha256:7efd08279c13dd68e0271507adc9cf5719c655a9f7d218a63a9fb673378713ca
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JSON: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_MD: true