name: Media Definition Validator
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        # Checkout the head ref instead of the PR branch that github creates.
        ref: ${{ github.head_ref }}
    - name: Setup Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install and build
      run: |
        npm ci
        npm run compile
    - name: Run status checks
      run: node dist/validator.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}